export const projects = [
  {
    title: 'CodeX Chatbot',
    description:
      'Using Vite, this app was built using vanilla javascript, Node.js and Express with an OpenAI NLP API. ',
    image: '/images/CX.png',
    tags: ['React', 'Node', 'Express'],
    source: 'https://github.com/ModouLaminJagne/CodeX',
    visit: 'https://code-x-beta.vercel.app/',
    id: 0,
  },
  {
    title: 'QuoteGen',
    description:
      "A Quote genereator app that gives random tech quotes and their authors, built with HTML, CSS & JAVASCRIPT with the. The HTML is generated by OpenAI's ChatGPT.",
    image: '/images/QG.png',
    tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://github.com/ModouLaminJagne/QuoteGen',
    visit: 'https://techquotes.netlify.app/',
    id: 1,
  },
  {
    title: 'AMC Website',
    description:
      'A website built for a client for his buisness. Built with raw HTM, Biootstrap and Javascript',
    image: '/images/AW.png',
    tags: ['HTML', 'Bootstrp', 'JavaScript'],
    source: 'https://github.com/ModouLaminJagne/AMC-website',
    visit: 'https://amcweb.netlify.app/',
    id: 2,
  },
  {
    title: 'AppaChat',
    description:
      'This is a full Realtime Chat Application, with features like any other chat app. Users can exchange text messages, pictures etc.',
    image: '/images/AC.png',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://github.com/ModouLaminJagne/AppaChat',
    visit: 'https://appachat.netlify.app/',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2020, text: 'Started my journey with HTML nad CSS.', },
  { year: 2021, text: 'learnt JAVASCRIPT with small projects.', },
  { year: 2022, text: 'Learnt REACT & PYTHON and started teaching JS.', },
  { year: 2023, text: 'Continuing to laern new technologies.', },
  // { year: 2021, text: 'Started my own platform', },
];